### PR TITLE
README - Fix quotes

### PR DESCRIPTION
**Pull request by lifeiteng**

### CODE REVIEW

**Comment by acassirer** [comment]
Hey,

Thanks a lot for contributing to Reverb! I'm afraid that we currently are unable to accept PRs due our current integration between our internal source control and GitHub only works in one direction. We are however working on making it bidirectional so once that is done then we'd be more than happy to accept this PR.

Thanks,
Albin

**Review by acassirer — APPROVED** [review]

**Comment by acassirer** [comment]
Hey @lifeiteng,

Sorry for the very long delay! 

If you could take a look and fix the merge conflict then I can merge can go ahead and merge the PR. Thanks again for contributing to Reverb!

**Comment by lifeiteng** [comment]
> Hey @lifeiteng,
> 
> Sorry for the very long delay!
> 
> If you could take a look and fix the merge conflict then I can merge can go ahead and merge the PR. Thanks again for contributing to Reverb!

DONE

**Review by acassirer — CHANGES_REQUESTED** [review]
This commit removes useful documentation. Could you please revert those changes so that it only fixes the quotes?

**Comment by lifeiteng** [comment]
> This commit removes useful documentation. Could you please revert those changes so that it only fixes the quotes?

I just modify one character. https://github.com/deepmind/reverb/pull/26/files

**Review by acassirer — APPROVED** [review]
LGTM. Sorry for the last comment. I was looking at one of the commits in isolation.

**Comment by acassirer** [comment]
The change was merged in https://github.com/deepmind/reverb/commit/5b62ac286838c5378c1526c716f9b2c92858ba50

Thanks a lot @lifeiteng for contributing to Reverb!

**Pull request closed without merging**
