### PR TITLE
Fix pip install problem in the demo notebook.

### PR DESCRIPTION
**Pull request by uduse**

### CODE REVIEW

**Comment by ebrevdo** [comment]
@acassirer we're still not able to accept pull requests, is that correct?

**Comment by uduse** [comment]
If that's the case, please make it clear in your [CONTRIBUTING.md](https://github.com/deepmind/reverb/blob/a5cde5992fd806de1aeec96a3f749a6787b03563/CONTRIBUTING.md) 🤔

**Comment by ebrevdo** [comment]
I recall we were making some progress on making this possible.  Will check.

**Review by acassirer — APPROVED** [review]
LGTM Thanks!

**Comment by acassirer** [comment]
The PR was integrated in https://github.com/deepmind/reverb/commit/4bdbb9895632d793e0fbdc509c1bfb23f1096b9d.

Thanks @uduse for contributing!

**Pull request closed without merging**
